//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoSoSucKhoe.Models.DBSQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class pathimage
    {
        public long id { get; set; }
        public string id2 { get; set; }
        public string path { get; set; }
    }
}
