//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoSoSucKhoe.Models.DBSQLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }

        public dbEntities(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pathimage> pathimages { get; set; }
        public virtual DbSet<sys_config> sys_config { get; set; }
        public virtual DbSet<sys_history> sys_history { get; set; }
        public virtual DbSet<sys_config1> sys_config1 { get; set; }
        public virtual DbSet<sys_history1> sys_history1 { get; set; }
        public virtual DbSet<sys_import> sys_import { get; set; }
        public virtual DbSet<sys_userconfig> sys_userconfig { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
    }
}
