//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoSoSucKhoe.Models.DBSQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_history1
    {
        public long id { get; set; }
        public string iduser { get; set; }
        public string typeinfo { get; set; }
        public string pathorherf { get; set; }
        public string action { get; set; }
        public string content { get; set; }
        public System.DateTime times { get; set; }
    }
}
