//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoSoSucKhoe.Models.DBSQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_import
    {
        public long id { get; set; }
        public string user { get; set; }
        public string action { get; set; }
        public string f0 { get; set; }
        public string f1 { get; set; }
        public string f2 { get; set; }
        public string f3 { get; set; }
        public string f4 { get; set; }
        public string f5 { get; set; }
        public string f6 { get; set; }
        public string f7 { get; set; }
        public string f8 { get; set; }
        public string f9 { get; set; }
        public string f10 { get; set; }
        public string f11 { get; set; }
        public string f12 { get; set; }
        public string f13 { get; set; }
        public string f14 { get; set; }
        public string f15 { get; set; }
        public string f16 { get; set; }
        public string f17 { get; set; }
        public string f18 { get; set; }
        public string f19 { get; set; }
        public string f20 { get; set; }
        public string f21 { get; set; }
        public string f22 { get; set; }
        public string f23 { get; set; }
        public string f24 { get; set; }
        public string f25 { get; set; }
        public string f26 { get; set; }
        public string f27 { get; set; }
        public string f28 { get; set; }
        public string f29 { get; set; }
        public string f30 { get; set; }
        public string f31 { get; set; }
        public string f32 { get; set; }
        public string f33 { get; set; }
        public string f34 { get; set; }
        public string f35 { get; set; }
        public string f36 { get; set; }
        public string f37 { get; set; }
        public string f38 { get; set; }
        public string f39 { get; set; }
        public string f40 { get; set; }
        public string f41 { get; set; }
        public string f42 { get; set; }
        public string f43 { get; set; }
        public string f44 { get; set; }
        public string f45 { get; set; }
        public string f46 { get; set; }
        public string f47 { get; set; }
        public string f48 { get; set; }
        public string f49 { get; set; }
    }
}
