//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoSoSucKhoe.Models.DBSQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public string iduser { get; set; }
        public string pass { get; set; }
        public string hoten { get; set; }
        public string ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public System.DateTime ngaytao { get; set; }
        public Nullable<System.DateTime> lancuoi { get; set; }
        public string ghichu { get; set; }
        public int idgroup { get; set; }
    }
}
